### ISSUE TITLE
請問專案功能有完成嗎？

### ISSUE THREAD

**Issue by mmmaaaxxx77** [poga/mooontag#2]
您好, 不小心看到這個專案, 覺得很不錯～
不過測試了一下, 似乎部分功能尚未完成？

**Comment by poga** [comment]
尚未實做 label 跟 text 的功能。 要幫忙嗎？ :)

**Comment by mmmaaaxxx77** [comment]
我將其他功能完成了, 
真的很漂亮耶！
請問這個有版權嗎？
我和同事想做一些印出來貼在電腦上 :)

**Comment by poga** [comment]
專案本身是 CC0（公眾領域），做出來的成果屬於製作者喔

願意把做好的功能分享出來嗎？ XD

**Comment by mmmaaaxxx77** [comment]
好的, 週末整理一下再發PR給您～
